#服务端口配置
server:
  port: 9999


spring:
  ##数据源配置
  datasource:
    #Mysql连接驱动
    driver-class-name: com.mysql.jdbc.Driver
    #Mysql连接账号
    username: root
    #Mysql连接密码
    password: 123456
    #Mysql连接地址
    url: jdbc:mysql://localhost:3306/springboot-activiti?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    initsize: 10
    maxActive: 20
    minIdle: 10
    maxWait: 120000
    poolPreparedStatements: false
    maxOpenPreparedStatements: -1
    validationQuery: select 1
    testOnborrow: true
    testOnReturn: true
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 120000

  ##工作流activiti配置
  activiti:
    #自动检查、部署流程定义文件，，检查resuorces->processes下是否有流程定义文件，没有则false
    check-process-definitions: true
    #自动更新数据库表结构
    database-schema-update: true
    #流程定义文件的存放目录前缀(默认目录是resource下的processes目录,在自定义目录存放的情况下可配置此属性指定)
    process-definition-location-prefix: classpath:/processes/
    #流程定义文件的存放目录后缀
    #process-definition-location-suffixes:


  #页面配置
  thymeleaf:
    cache: false # 开发时关闭缓存,不然没法看到实时页面
    prefix:
      classpath: /templates   # 访问template下的html文件需要配置模板，映射
    suffix: .html
