spring:
  redis:
    #Redis服务器连接地址
    host: 127.0.0.1
    #Redis服务器连接端口
    port: 6379
    #Redis数据库(默认为0)
    database: 1
    #Redis数据库连接密码
    password:
    #连接超时时间（毫秒）
    timeout: 10000ms
    #\lettuce连接池配置(也可以使用Jedispool连接池,推荐使用lettuce连接池)
    lettuce:
      pool:
        #连接池中的最大空闲连接
        max-idle: 8
        #连接池中的最小空闲连接
        min-idle: 0
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 8

