server:
  # https加密端口
  port: 443
  # SSL证书相关配置
  ssl:
    # 证书路径
    key-store: classpath:keystore.p12
    # 证书秘钥
    key-store-password: 123456
    # 证书类型
    key-store-type: PKCS12
    # 证书别名
    key-alias: tomcat


#HTML页面配置
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html