#######SpringBoot测试环境########
#端口
server:
  port: 8888
  servlet:
    context-path: /springboot-pringLog

#spring应用程序名称
spring:
  application:
    name: springboot-printLog

#自定义项目加载信息
app:
  info:
    #组名
    project-group: '@project.parent.groupId@'
    #项目名
    project-name: ${spring.application.name}
    #项目作者
    project-author: Thinkingcao
    #项目描述
    project-description: '@project.description@'
    #项目编码
    project-sourceEncoding: '@project.build.sourceEncoding@'
    #SpringBoot版本
    project-springboot-version: '@spring-boot.version@'
    #项目版本
    project-version: '@project.version@'
    #项目访问上下文名称
    project-context: ${server.servlet.context-path}
    #博客网站
    blog-url: https://thinkingcao.blog.csdn.net/