#二维码配置
qrcode:
  info:
    #二维码编码
    charset: utf-8
    #二维码宽度
    qrWidth: 300
    #二维码高度
    qrHeight: 300
    #logo宽度
    logoWidth: 120
    #logo高度
    logoHeight: 120
    #二维码图片类型
    qrPicType: jpg


#打印输出debug级别日志
logging:
  level:
    com.thinkingcao.springboot.qrcode: debug

