#二维码配置
qrcode:
  info:
    #二维码编码
    charset: utf-8
    #二维码宽度
    qrWidth: 300
    #二维码高度
    qrHeight: 300
    #logo宽度
    logoWidth: 30
    #logo高度
    logoHeight: 30
    #二维码图片类型
    qrPicType: jpg

#spring:
#  resources:
#    static-locations: classpath:/static/images
