#端口配置
server:
  port: 8080

spring:
  #HTML配置
  thymeleaf:
    # 模板存放路径
    prefix: classpath:/templates/
    # 模板后缀
    suffix: .html
    # 是否启用
    enabled: true
    # 模板编码
    encoding: UTF-8
    # 启用缓存，建议生产开启
    cache: false
  #文件上传配置
  servlet:
    multipart:
      #是否支持批量上传(默认为true)
      enabled: true
      #上传文件的临时目录
      location: D:\Images\upload\fileUpload
      #上传文件最大问1M(默认1M，根据自身业务控制即可)
      max-file-size: 50MB
      #设置总上传的数据大小10M(默认值10M，根据自身业务控制即可)
      max-request-size: 100MB
      #文件大小阈值，当大于这个阈值时将写入到磁盘，否则存在内存中（默认值0 一般情况下不用特意修改）
      file-size-threshold: 0
