
##spring配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot-mybatis-plus
    username: root
    password: kU#m5eHY5iTiQj#q

##mybatis-plus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


##logback配置
logback:
  logDir: log/dev

logging:
  level:
    com.thinkingcao.springbootmybatisplus.service.impl: trace
    com.thinkingcao.springbootmybatisplus..controller: trace