spring:
  application:
    name: springboot-mongodb
  data:
    mongodb:
      host: localhost
      username: test
      password: 123456
      port: 27017
      uri: mongodb://localhost/test
      database: springboot-mongodb