#Redis配置
spring:
  redis:
    #Redis服务器
    host: 127.0.0.1
    #Redis端口
    port: 6379
    #Redis密码(默认没有)
    password:
    #Redis数据库索引（默认为0）
    database: 0
    #这里标明使用lettuce配置
    lettuce:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 32
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 300ms
        #连接池中的最大空闲连接
        max-idle: 16
        #连接池中的最小空闲连接
        min-idle: 8
        #连接超时时间（毫秒）
        timeout: 1000


  ##数据库配置
  datasource:
    name: test
    url: jdbc:mysql://127.0.0.1:3306/springboot-token
    username: root
    password: 123456
    ## 数据源配置
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20


#Mybatis配置
mybatis:
  #mybatis配置文件位置
  config-location: classpath:config/mybatis-config.xml
  #mapper.xml 文件地址
  mapper-locations: classpath:mapper/*.xml
  #实体类别名
  type-aliases-package: com.thinkingcao.springboot.entity


##日志配置
logging:
  level:
    com.thinkingcao.springboot.token.mapper: debug